spring:
  application:
    name: product-service
  datasource:
#    url: jdbc:postgresql://localhost:5432/productdb
    url: jdbc:postgresql://ep-crimson-forest-adw6y495-pooler.c-2.us-east-1.aws.neon.tech/productdb?sslmode=require&channel_binding=require
#    username: postgres
    username: neondb_owner
    password: npg_imnTW4sXJU8q
#    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
server:
  port: 8081
